name: zego_uikit_prebuilt_video_conference
description: PrebuiltVideoConference is a full-featured Video Conference kit that provides a ready-made group voice/video chat, in-room message, dynamic layout, member list, etc.
version: 2.3.2
homepage: https://www.zegocloud.com/
repository: https://github.com/ZEGOCLOUD/zego_uikit_prebuilt_video_conference_flutter
screenshots:
  - description: "Video Conference Kit for pub.dev preview"
    path: images/preview.jpg

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  zego_uikit: ^2.7.1

  http: ^0.13.4
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  import_sorter: ^4.6.0  # run 'flutter pub run import_sorter:main'
  dart_code_metrics: any

flutter:
  assets:
    - assets/icons/
